server:
  port: 8005
  init-parameters:
    development: true

spring:
  datasource:
    name: test
    url: jdbc:mysql://rm-2ze07n2vsa5746kqpko.mysql.rds.aliyuncs.com:3306/p2p?useSSL=false&useAffectedRows=true
    username: root
    password: 977116lwcGCK
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/page/
  thymeleaf:
    cache: false
    enabled: false
  jpa:
    show-sql: true
    open-in-view: false

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  # mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hg.p2p_2.biz.*.mapper  # 注意：对应实体类的路径

#logging:
#  config: classpath:log4j2-spring.xml




